### ISSUE TITLE
feature request: support breads from other mods

### ISSUE THREAD

**Issue by Lazerbeak12345** [SmallJoker/stapled_bread#1]
If another mod adds bread, it'd be nice if aliases were used between this mod and the mod that adds the bread to ensure that it is the same bread.

In particular integration with these would be great:

- https://content.minetest.net/packages/Annalysa/sandwiches/
- https://content.minetest.net/packages/TenPlus1/farming/

**Comment by Lazerbeak12345** [comment]
Supporting _more_ bread types would be nice as well, though not really what I'm asking for.

I'm willing to PR this.

**Comment by SmallJoker** [comment]
Cool idea. I also made it easier to remove the bread from the sides and fixed an issue where the a stack size of 1 would staple the empty hand itself.

10518c3  Please report back if there's an issue :)

**Comment by Lazerbeak12345** [comment]
Amazing. 10/10 commit

**Comment by Lazerbeak12345** [comment]
Oh! Just realized, you'll need to update the contentdb description
